// <auto-generated />
namespace TrabalhoTcc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adicionandologinclientes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionandologinclientes));
        
        string IMigrationMetadata.Id
        {
            get { return "201808241702298_adicionando login clientes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
